language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t rahul3vk/docker-react -f Dockerfile.dev .

script: 
    - docker run -e CI=true rahul3vk/docker-react npm run test